<?php

use Illuminate\Database\Seeder;

class AdsviewTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('adsview')->delete();
        
        \DB::table('adsview')->insert(array (
            0 => 
            array (
                'id' => 21,
                'is_logged_in' => 0,
                'from_url' => 'http://localhost:8000/',
                'landing_page_url' => '/ad/1',
                'ad_id' => 1,
                'ip' => '::1',
                'user_id' => NULL,
                'device' => 'Web',
                'updated_at' => '2016-11-24 14:26:03',
                'created_at' => '2016-11-24 14:26:03',
            ),
            1 => 
            array (
                'id' => 22,
                'is_logged_in' => 0,
                'from_url' => 'http://localhost:8000/',
                'landing_page_url' => '/ad/1',
                'ad_id' => 1,
                'ip' => '::1',
                'user_id' => NULL,
                'device' => 'Web',
                'updated_at' => '2016-11-24 14:28:18',
                'created_at' => '2016-11-24 14:28:18',
            ),
            2 => 
            array (
                'id' => 23,
                'is_logged_in' => 0,
                'from_url' => 'http://localhost:8000/ads',
                'landing_page_url' => '/ad/1',
                'ad_id' => 1,
                'ip' => '::1',
                'user_id' => NULL,
                'device' => 'Web',
                'updated_at' => '2016-11-24 14:28:23',
                'created_at' => '2016-11-24 14:28:23',
            ),
            3 => 
            array (
                'id' => 24,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/admin/views',
                'landing_page_url' => '/ad/1',
                'ad_id' => 1,
                'ip' => '::1',
                'user_id' => 1,
                'device' => 'Web',
                'updated_at' => '2016-11-24 14:31:13',
                'created_at' => '2016-11-24 14:31:13',
            ),
            4 => 
            array (
                'id' => 25,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/admin/views',
                'landing_page_url' => '/ad/2',
                'ad_id' => 2,
                'ip' => '::1',
                'user_id' => 1,
                'device' => 'Web',
                'updated_at' => '2016-11-24 14:31:15',
                'created_at' => '2016-11-24 14:31:15',
            ),
            5 => 
            array (
                'id' => 26,
                'is_logged_in' => 0,
                'from_url' => 'http://localhost:8000/',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => NULL,
                'device' => 'Web',
                'updated_at' => '2016-11-24 14:45:14',
                'created_at' => '2016-11-24 14:45:14',
            ),
            6 => 
            array (
                'id' => 27,
                'is_logged_in' => 0,
                'from_url' => 'http://localhost:8000/',
                'landing_page_url' => '/ad/5',
                'ad_id' => 5,
                'ip' => '::1',
                'user_id' => NULL,
                'device' => 'Web',
                'updated_at' => '2016-11-24 14:45:15',
                'created_at' => '2016-11-24 14:45:15',
            ),
            7 => 
            array (
                'id' => 28,
                'is_logged_in' => 0,
                'from_url' => 'http://localhost:8000/',
                'landing_page_url' => '/ad/6',
                'ad_id' => 6,
                'ip' => '::1',
                'user_id' => NULL,
                'device' => 'Web',
                'updated_at' => '2016-11-24 14:45:17',
                'created_at' => '2016-11-24 14:45:17',
            ),
            8 => 
            array (
                'id' => 29,
                'is_logged_in' => 0,
                'from_url' => 'http://localhost:8000/',
                'landing_page_url' => '/ad/9',
                'ad_id' => 9,
                'ip' => '::1',
                'user_id' => NULL,
                'device' => 'Web',
                'updated_at' => '2016-11-24 14:46:59',
                'created_at' => '2016-11-24 14:46:59',
            ),
            9 => 
            array (
                'id' => 30,
                'is_logged_in' => 0,
                'from_url' => 'http://localhost:8000/',
                'landing_page_url' => '/ad/8',
                'ad_id' => 8,
                'ip' => '::1',
                'user_id' => NULL,
                'device' => 'Web',
                'updated_at' => '2016-11-24 14:47:01',
                'created_at' => '2016-11-24 14:47:01',
            ),
            10 => 
            array (
                'id' => 31,
                'is_logged_in' => 0,
                'from_url' => 'http://localhost:8000/',
                'landing_page_url' => '/ad/7',
                'ad_id' => 7,
                'ip' => '::1',
                'user_id' => NULL,
                'device' => 'Web',
                'updated_at' => '2016-11-24 14:47:02',
                'created_at' => '2016-11-24 14:47:02',
            ),
            11 => 
            array (
                'id' => 32,
                'is_logged_in' => 0,
                'from_url' => 'http://localhost:8000/',
                'landing_page_url' => '/ad/8',
                'ad_id' => 8,
                'ip' => '::1',
                'user_id' => NULL,
                'device' => 'Web',
                'updated_at' => '2016-11-24 14:47:03',
                'created_at' => '2016-11-24 14:47:03',
            ),
            12 => 
            array (
                'id' => 33,
                'is_logged_in' => 0,
                'from_url' => 'http://localhost:8000/',
                'landing_page_url' => '/ad/8',
                'ad_id' => 8,
                'ip' => '::1',
                'user_id' => NULL,
                'device' => 'Web',
                'updated_at' => '2016-11-24 14:47:05',
                'created_at' => '2016-11-24 14:47:05',
            ),
            13 => 
            array (
                'id' => 34,
                'is_logged_in' => 0,
                'from_url' => 'http://localhost:8000/',
                'landing_page_url' => '/ad/7',
                'ad_id' => 7,
                'ip' => '::1',
                'user_id' => NULL,
                'device' => 'Web',
                'updated_at' => '2016-11-24 14:47:06',
                'created_at' => '2016-11-24 14:47:06',
            ),
            14 => 
            array (
                'id' => 35,
                'is_logged_in' => 0,
                'from_url' => 'http://localhost:8000/',
                'landing_page_url' => '/ad/8',
                'ad_id' => 8,
                'ip' => '::1',
                'user_id' => NULL,
                'device' => 'Web',
                'updated_at' => '2016-11-24 14:47:07',
                'created_at' => '2016-11-24 14:47:07',
            ),
            15 => 
            array (
                'id' => 36,
                'is_logged_in' => 0,
                'from_url' => 'http://localhost:8000/',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => NULL,
                'device' => 'Web',
                'updated_at' => '2016-11-24 14:48:53',
                'created_at' => '2016-11-24 14:48:53',
            ),
            16 => 
            array (
                'id' => 37,
                'is_logged_in' => 0,
                'from_url' => 'http://localhost:8000/',
                'landing_page_url' => '/ad/1',
                'ad_id' => 1,
                'ip' => '::1',
                'user_id' => NULL,
                'device' => 'Web',
                'updated_at' => '2016-11-24 14:49:00',
                'created_at' => '2016-11-24 14:49:00',
            ),
            17 => 
            array (
                'id' => 38,
                'is_logged_in' => 0,
                'from_url' => 'http://localhost:8000/',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => NULL,
                'device' => 'Web',
                'updated_at' => '2016-11-24 14:53:32',
                'created_at' => '2016-11-24 14:53:32',
            ),
            18 => 
            array (
                'id' => 39,
                'is_logged_in' => 0,
                'from_url' => 'http://localhost:8000/',
                'landing_page_url' => '/ad/1',
                'ad_id' => 1,
                'ip' => '::1',
                'user_id' => NULL,
                'device' => 'Web',
                'updated_at' => '2016-11-24 14:53:34',
                'created_at' => '2016-11-24 14:53:34',
            ),
            19 => 
            array (
                'id' => 40,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/',
                'landing_page_url' => '/ad/1',
                'ad_id' => 1,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:12:56',
                'created_at' => '2016-11-24 15:12:56',
            ),
            20 => 
            array (
                'id' => 41,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/',
                'landing_page_url' => '/ad/1',
                'ad_id' => 1,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:13:23',
                'created_at' => '2016-11-24 15:13:23',
            ),
            21 => 
            array (
                'id' => 42,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ads',
                'landing_page_url' => '/ad/1',
                'ad_id' => 1,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:13:41',
                'created_at' => '2016-11-24 15:13:41',
            ),
            22 => 
            array (
                'id' => 43,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ads',
                'landing_page_url' => '/ad/1',
                'ad_id' => 1,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:14:57',
                'created_at' => '2016-11-24 15:14:57',
            ),
            23 => 
            array (
                'id' => 44,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ads',
                'landing_page_url' => '/ad/1',
                'ad_id' => 1,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:17:51',
                'created_at' => '2016-11-24 15:17:51',
            ),
            24 => 
            array (
                'id' => 45,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ads',
                'landing_page_url' => '/ad/1',
                'ad_id' => 1,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:18:56',
                'created_at' => '2016-11-24 15:18:56',
            ),
            25 => 
            array (
                'id' => 46,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ads',
                'landing_page_url' => '/ad/1',
                'ad_id' => 1,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:24:19',
                'created_at' => '2016-11-24 15:24:19',
            ),
            26 => 
            array (
                'id' => 47,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ads',
                'landing_page_url' => '/ad/1',
                'ad_id' => 1,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:24:48',
                'created_at' => '2016-11-24 15:24:48',
            ),
            27 => 
            array (
                'id' => 48,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ads',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:24:54',
                'created_at' => '2016-11-24 15:24:54',
            ),
            28 => 
            array (
                'id' => 49,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ads',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:25:16',
                'created_at' => '2016-11-24 15:25:16',
            ),
            29 => 
            array (
                'id' => 50,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ads',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:25:43',
                'created_at' => '2016-11-24 15:25:43',
            ),
            30 => 
            array (
                'id' => 51,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ads',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:26:04',
                'created_at' => '2016-11-24 15:26:04',
            ),
            31 => 
            array (
                'id' => 52,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ads',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:26:38',
                'created_at' => '2016-11-24 15:26:38',
            ),
            32 => 
            array (
                'id' => 53,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ads',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:28:56',
                'created_at' => '2016-11-24 15:28:56',
            ),
            33 => 
            array (
                'id' => 54,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ads',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:29:32',
                'created_at' => '2016-11-24 15:29:32',
            ),
            34 => 
            array (
                'id' => 55,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ads',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:29:39',
                'created_at' => '2016-11-24 15:29:39',
            ),
            35 => 
            array (
                'id' => 56,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ads',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:29:41',
                'created_at' => '2016-11-24 15:29:41',
            ),
            36 => 
            array (
                'id' => 57,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:31:28',
                'created_at' => '2016-11-24 15:31:28',
            ),
            37 => 
            array (
                'id' => 58,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:31:31',
                'created_at' => '2016-11-24 15:31:31',
            ),
            38 => 
            array (
                'id' => 59,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:31:52',
                'created_at' => '2016-11-24 15:31:52',
            ),
            39 => 
            array (
                'id' => 60,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:33:10',
                'created_at' => '2016-11-24 15:33:10',
            ),
            40 => 
            array (
                'id' => 61,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:33:12',
                'created_at' => '2016-11-24 15:33:12',
            ),
            41 => 
            array (
                'id' => 62,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:33:51',
                'created_at' => '2016-11-24 15:33:51',
            ),
            42 => 
            array (
                'id' => 63,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:34:24',
                'created_at' => '2016-11-24 15:34:24',
            ),
            43 => 
            array (
                'id' => 64,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:34:43',
                'created_at' => '2016-11-24 15:34:43',
            ),
            44 => 
            array (
                'id' => 65,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:34:52',
                'created_at' => '2016-11-24 15:34:52',
            ),
            45 => 
            array (
                'id' => 66,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:35:05',
                'created_at' => '2016-11-24 15:35:05',
            ),
            46 => 
            array (
                'id' => 67,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:35:34',
                'created_at' => '2016-11-24 15:35:34',
            ),
            47 => 
            array (
                'id' => 68,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:36:30',
                'created_at' => '2016-11-24 15:36:30',
            ),
            48 => 
            array (
                'id' => 69,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:36:38',
                'created_at' => '2016-11-24 15:36:38',
            ),
            49 => 
            array (
                'id' => 70,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:37:31',
                'created_at' => '2016-11-24 15:37:31',
            ),
            50 => 
            array (
                'id' => 71,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:37:42',
                'created_at' => '2016-11-24 15:37:42',
            ),
            51 => 
            array (
                'id' => 72,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:37:49',
                'created_at' => '2016-11-24 15:37:49',
            ),
            52 => 
            array (
                'id' => 73,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:37:50',
                'created_at' => '2016-11-24 15:37:50',
            ),
            53 => 
            array (
                'id' => 74,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:37:57',
                'created_at' => '2016-11-24 15:37:57',
            ),
            54 => 
            array (
                'id' => 75,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:38:04',
                'created_at' => '2016-11-24 15:38:04',
            ),
            55 => 
            array (
                'id' => 76,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:38:30',
                'created_at' => '2016-11-24 15:38:30',
            ),
            56 => 
            array (
                'id' => 77,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:38:43',
                'created_at' => '2016-11-24 15:38:43',
            ),
            57 => 
            array (
                'id' => 78,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:38:52',
                'created_at' => '2016-11-24 15:38:52',
            ),
            58 => 
            array (
                'id' => 79,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:39:01',
                'created_at' => '2016-11-24 15:39:01',
            ),
            59 => 
            array (
                'id' => 80,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:40:31',
                'created_at' => '2016-11-24 15:40:31',
            ),
            60 => 
            array (
                'id' => 81,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:42:25',
                'created_at' => '2016-11-24 15:42:25',
            ),
            61 => 
            array (
                'id' => 82,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4',
                'landing_page_url' => '/ad/4?editComment=9',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:42:27',
                'created_at' => '2016-11-24 15:42:27',
            ),
            62 => 
            array (
                'id' => 83,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4?editComment=9',
                'landing_page_url' => '/ad/4?editComment=10',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:42:29',
                'created_at' => '2016-11-24 15:42:29',
            ),
            63 => 
            array (
                'id' => 84,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4?editComment=9',
                'landing_page_url' => '/ad/4?editComment=10',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:46:27',
                'created_at' => '2016-11-24 15:46:27',
            ),
            64 => 
            array (
                'id' => 85,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4?editComment=9',
                'landing_page_url' => '/ad/4?editComment=10',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:46:39',
                'created_at' => '2016-11-24 15:46:39',
            ),
            65 => 
            array (
                'id' => 86,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4?editComment=9',
                'landing_page_url' => '/ad/4?editComment=10',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:47:23',
                'created_at' => '2016-11-24 15:47:23',
            ),
            66 => 
            array (
                'id' => 87,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4?editComment=9',
                'landing_page_url' => '/ad/4?editComment=10',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:47:50',
                'created_at' => '2016-11-24 15:47:50',
            ),
            67 => 
            array (
                'id' => 88,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4?editComment=9',
                'landing_page_url' => '/ad/4?editComment=10',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:47:57',
                'created_at' => '2016-11-24 15:47:57',
            ),
            68 => 
            array (
                'id' => 89,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4?editComment=9',
                'landing_page_url' => '/ad/4?editComment=10',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:50:55',
                'created_at' => '2016-11-24 15:50:55',
            ),
            69 => 
            array (
                'id' => 90,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4?editComment=9',
                'landing_page_url' => '/ad/4?editComment=10',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:51:53',
                'created_at' => '2016-11-24 15:51:53',
            ),
            70 => 
            array (
                'id' => 91,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4?editComment=9',
                'landing_page_url' => '/ad/4?editComment=10',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:52:29',
                'created_at' => '2016-11-24 15:52:29',
            ),
            71 => 
            array (
                'id' => 92,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4',
                'landing_page_url' => '/ad/4?editComment=11',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:52:45',
                'created_at' => '2016-11-24 15:52:45',
            ),
            72 => 
            array (
                'id' => 93,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4?editComment=11',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:53:03',
                'created_at' => '2016-11-24 15:53:03',
            ),
            73 => 
            array (
                'id' => 94,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4?editComment=11',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:53:28',
                'created_at' => '2016-11-24 15:53:28',
            ),
            74 => 
            array (
                'id' => 95,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4',
                'landing_page_url' => '/ad/4?editComment=10',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:53:33',
                'created_at' => '2016-11-24 15:53:33',
            ),
            75 => 
            array (
                'id' => 96,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4',
                'landing_page_url' => '/ad/4?editComment=10',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:53:41',
                'created_at' => '2016-11-24 15:53:41',
            ),
            76 => 
            array (
                'id' => 97,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4?editComment=10',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:53:54',
                'created_at' => '2016-11-24 15:53:54',
            ),
            77 => 
            array (
                'id' => 98,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4?editComment=10',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:55:06',
                'created_at' => '2016-11-24 15:55:06',
            ),
            78 => 
            array (
                'id' => 99,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4?editComment=10',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:55:20',
                'created_at' => '2016-11-24 15:55:20',
            ),
            79 => 
            array (
                'id' => 100,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4?editComment=10',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:55:33',
                'created_at' => '2016-11-24 15:55:33',
            ),
            80 => 
            array (
                'id' => 101,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4?editComment=10',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:55:51',
                'created_at' => '2016-11-24 15:55:51',
            ),
            81 => 
            array (
                'id' => 102,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4?editComment=10',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:56:11',
                'created_at' => '2016-11-24 15:56:11',
            ),
            82 => 
            array (
                'id' => 103,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4?editComment=10',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:56:27',
                'created_at' => '2016-11-24 15:56:27',
            ),
            83 => 
            array (
                'id' => 104,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4?editComment=10',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:56:36',
                'created_at' => '2016-11-24 15:56:36',
            ),
            84 => 
            array (
                'id' => 105,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:56:41',
                'created_at' => '2016-11-24 15:56:41',
            ),
            85 => 
            array (
                'id' => 106,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:56:44',
                'created_at' => '2016-11-24 15:56:44',
            ),
            86 => 
            array (
                'id' => 107,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:56:52',
                'created_at' => '2016-11-24 15:56:52',
            ),
            87 => 
            array (
                'id' => 108,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4',
                'landing_page_url' => '/ad/4?editComment=12',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:56:56',
                'created_at' => '2016-11-24 15:56:56',
            ),
            88 => 
            array (
                'id' => 109,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4?editComment=12',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:57:00',
                'created_at' => '2016-11-24 15:57:00',
            ),
            89 => 
            array (
                'id' => 110,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4?editComment=12',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:57:36',
                'created_at' => '2016-11-24 15:57:36',
            ),
            90 => 
            array (
                'id' => 111,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4?editComment=12',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:57:50',
                'created_at' => '2016-11-24 15:57:50',
            ),
            91 => 
            array (
                'id' => 112,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4?editComment=12',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:58:22',
                'created_at' => '2016-11-24 15:58:22',
            ),
            92 => 
            array (
                'id' => 113,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4?editComment=12',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:58:34',
                'created_at' => '2016-11-24 15:58:34',
            ),
            93 => 
            array (
                'id' => 114,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4?editComment=12',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:58:59',
                'created_at' => '2016-11-24 15:58:59',
            ),
            94 => 
            array (
                'id' => 115,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4?editComment=12',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:59:08',
                'created_at' => '2016-11-24 15:59:08',
            ),
            95 => 
            array (
                'id' => 116,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4?editComment=12',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 15:59:56',
                'created_at' => '2016-11-24 15:59:56',
            ),
            96 => 
            array (
                'id' => 117,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4?editComment=12',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 16:00:16',
                'created_at' => '2016-11-24 16:00:16',
            ),
            97 => 
            array (
                'id' => 118,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4?editComment=12',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 16:00:32',
                'created_at' => '2016-11-24 16:00:32',
            ),
            98 => 
            array (
                'id' => 119,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4?editComment=12',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 16:00:38',
                'created_at' => '2016-11-24 16:00:38',
            ),
            99 => 
            array (
                'id' => 120,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4?editComment=12',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 16:01:11',
                'created_at' => '2016-11-24 16:01:11',
            ),
            100 => 
            array (
                'id' => 121,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4?editComment=12',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 16:01:24',
                'created_at' => '2016-11-24 16:01:24',
            ),
            101 => 
            array (
                'id' => 122,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4?editComment=12',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 16:01:38',
                'created_at' => '2016-11-24 16:01:38',
            ),
            102 => 
            array (
                'id' => 123,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4?editComment=12',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 16:01:39',
                'created_at' => '2016-11-24 16:01:39',
            ),
            103 => 
            array (
                'id' => 124,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4?editComment=12',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 16:01:52',
                'created_at' => '2016-11-24 16:01:52',
            ),
            104 => 
            array (
                'id' => 125,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4?editComment=12',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 16:02:25',
                'created_at' => '2016-11-24 16:02:25',
            ),
            105 => 
            array (
                'id' => 126,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4?editComment=12',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 16:02:47',
                'created_at' => '2016-11-24 16:02:47',
            ),
            106 => 
            array (
                'id' => 127,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4?editComment=12',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 16:03:08',
                'created_at' => '2016-11-24 16:03:08',
            ),
            107 => 
            array (
                'id' => 128,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4?editComment=12',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 16:03:08',
                'created_at' => '2016-11-24 16:03:08',
            ),
            108 => 
            array (
                'id' => 129,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4',
                'landing_page_url' => '/ad/4?editComment=10',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 16:03:10',
                'created_at' => '2016-11-24 16:03:10',
            ),
            109 => 
            array (
                'id' => 130,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4?editComment=10',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 16:03:13',
                'created_at' => '2016-11-24 16:03:13',
            ),
            110 => 
            array (
                'id' => 131,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4?editComment=10',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 16:05:25',
                'created_at' => '2016-11-24 16:05:25',
            ),
            111 => 
            array (
                'id' => 132,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4?editComment=10',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 16:05:44',
                'created_at' => '2016-11-24 16:05:44',
            ),
            112 => 
            array (
                'id' => 133,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4?editComment=10',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 16:06:06',
                'created_at' => '2016-11-24 16:06:06',
            ),
            113 => 
            array (
                'id' => 134,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4?editComment=10',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 16:06:14',
                'created_at' => '2016-11-24 16:06:14',
            ),
            114 => 
            array (
                'id' => 135,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4?editComment=10',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 16:06:26',
                'created_at' => '2016-11-24 16:06:26',
            ),
            115 => 
            array (
                'id' => 136,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4?editComment=10',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 16:06:34',
                'created_at' => '2016-11-24 16:06:34',
            ),
            116 => 
            array (
                'id' => 137,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4?editComment=10',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 16:06:49',
                'created_at' => '2016-11-24 16:06:49',
            ),
            117 => 
            array (
                'id' => 138,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4?editComment=10',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 16:06:57',
                'created_at' => '2016-11-24 16:06:57',
            ),
            118 => 
            array (
                'id' => 139,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4?editComment=10',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 16:07:11',
                'created_at' => '2016-11-24 16:07:11',
            ),
            119 => 
            array (
                'id' => 140,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4?editComment=10',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 16:07:13',
                'created_at' => '2016-11-24 16:07:13',
            ),
            120 => 
            array (
                'id' => 141,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4?editComment=10',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 16:07:21',
                'created_at' => '2016-11-24 16:07:21',
            ),
            121 => 
            array (
                'id' => 142,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4?editComment=10',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 16:07:33',
                'created_at' => '2016-11-24 16:07:33',
            ),
            122 => 
            array (
                'id' => 143,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4?editComment=10',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 16:07:43',
                'created_at' => '2016-11-24 16:07:43',
            ),
            123 => 
            array (
                'id' => 144,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 16:07:58',
                'created_at' => '2016-11-24 16:07:58',
            ),
            124 => 
            array (
                'id' => 145,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 16:08:02',
                'created_at' => '2016-11-24 16:08:02',
            ),
            125 => 
            array (
                'id' => 146,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/4',
                'landing_page_url' => '/ad/4',
                'ad_id' => 4,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-24 16:13:54',
                'created_at' => '2016-11-24 16:13:54',
            ),
            126 => 
            array (
                'id' => 147,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ads',
                'landing_page_url' => '/ad/1',
                'ad_id' => 1,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-25 11:20:16',
                'created_at' => '2016-11-25 11:20:16',
            ),
            127 => 
            array (
                'id' => 148,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ads',
                'landing_page_url' => '/ad/1',
                'ad_id' => 1,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-25 12:09:36',
                'created_at' => '2016-11-25 12:09:36',
            ),
            128 => 
            array (
                'id' => 149,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/1',
                'landing_page_url' => '/ad/1',
                'ad_id' => 1,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-25 12:09:42',
                'created_at' => '2016-11-25 12:09:42',
            ),
            129 => 
            array (
                'id' => 150,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ad/1',
                'landing_page_url' => '/ad/1',
                'ad_id' => 1,
                'ip' => '::1',
                'user_id' => 3,
                'device' => 'Web',
                'updated_at' => '2016-11-25 13:50:52',
                'created_at' => '2016-11-25 13:50:52',
            ),
            130 => 
            array (
                'id' => 151,
                'is_logged_in' => 1,
                'from_url' => 'http://localhost:8000/ads',
                'landing_page_url' => '/ad/1',
                'ad_id' => 1,
                'ip' => '::1',
                'user_id' => 1,
                'device' => 'Web',
                'updated_at' => '2016-11-25 14:50:59',
                'created_at' => '2016-11-25 14:50:59',
            ),
        ));
        
        
    }
}
